name: SonarQube Analysis

on:
  pull_request:
    branches: [ "main", "labs/dev" ]
    paths:
      - 'spring-petclinic/**'

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        working-directory: ./spring-petclinic
        run: mvn clean verify

      - name: Run SonarQube analysis
        working-directory: ./spring-petclinic
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=alex-project-ironhack \
            -Dsonar.projectName=alex-project-ironhack \
            -Dsonar.sources=src/main \
            -Dsonar.tests=src/test \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.java.test.binaries=target/test-classes \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
